services:
  my_zhi_hu_web:
    image: my_zhi_hu_web
    container_name: my_zhi_hu_web
    user: root
    restart: always
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile


